### ISSUE TITLE
Error: write EOF

### ISSUE THREAD

**Issue by mjot** [imagemin/imagemin-jpegoptim#7]
Hi,

I'm getting the following error when using imagemin-jpegoptim:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EOF
    at errnoException (net.js:904:11)
    at Object.afterWrite (net.js:720:19)

-----

Here is  my gulpfile:

    var gulp = require('gulp');
  
    var sass      = require('gulp-ruby-sass'),
        jpegoptim = require('imagemin-jpegoptim'),
        pngquant  = require('imagemin-pngquant'),
        imagemin  = require('gulp-imagemin');

    var paths = {
        imgSrc:  'html/src/img/**/*.{png,jpg,jpeg}',
        imgDst:  'html/img/'
    };

    // optimize images
    gulp.task('images', function() {

        return gulp.src(paths.imgSrc)
            .pipe(imagemin({
                progressive: true,
                use: [pngquant(),jpegoptim({ progressive: true, max: 50})]
            }))
            .pipe(gulp.dest(paths.imgDst));

    });

   ...

----

I hope someone can give me a hint how to fix this. :)

Thanks,
Martin

**Comment by jon64digital** [comment]
Exactly the same problem here on windows.

Gulp-imagemin - version 2.1.0
imagemin-jpegoptim - version 4.0.0

**Comment by Samsy** [comment]
Same here

**Comment by kevva** [comment]
Did you get any messages upon install?

**Comment by jmaleman** [comment]
I have the same problem running (Fatal error: write EOF) Grunt Task with Windows 7 x64
"grunt": "^0.4.5",
"grunt-contrib-imagemin": "^0.9.2",
"imagemin-jpegoptim": "^4.0.0"

**Comment by kevva** [comment]
Same question to you, did you get any errors upon installation?

**Comment by jmaleman** [comment]
No errors installation.
I try with Gulp and...
![captura](https://cloud.githubusercontent.com/assets/8301910/6212889/5c6572fe-b5ea-11e4-8979-848ae9bcfdb5.PNG)

**Comment by shinnn** [comment]
Same as https://github.com/imagemin/imagemin/issues/81

I'll fix this soon.

**Comment by shinnn** [comment]
Ah, I found another issue related to this.

@mjot @jon64digital @Samsy @jmaleman Would you mind building jpgoptim 1.4.2 on Windows and creating a pull request to fix imagemin/jpegoptim-bin#2 ?

**Comment by maranomynet** [comment]
Newest version of imagemin-jpegoptim still doesn't work on Windows.

```
Error: write EOF
    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:766:14)
```

**Comment by shinnn** [comment]
@maranomynet https://github.com/imagemin/imagemin-jpegoptim/issues/7#issuecomment-83762417

> Would you mind building jpegoptim 1.4.2 on Windows and creating a pull request to fix imagemin/jpegoptim-bin#2 ?

**Comment by maranomynet** [comment]
I've never compiled from source on Windows before.
Will give it a shot.

**Comment by shinnn** [comment]
Ah, not 1.4.2. Could you build the binary from [the latest `master` branch of tjko/jpegoptim](https://github.com/tjko/jpegoptim/tree/master)?

It includes an important fix for Windows. https://github.com/tjko/jpegoptim/commit/4e82d0cf2853874e604bb9efc8b6b98d36d8b036

> Will give it a shot.

Thanks. Really helpful :)

**Comment by maranomynet** [comment]
Installed MinGW. Cloned the tjko/jpegoptim repo, Ran .configure(.sh) sucessfully (it seems) but running `mingw32-make` gives this error:

```
mingw32-make: *** No targets specified and no makefile found.  Stop.
```

Have run out of ideas for now. Will resume later today.

**Comment by maranomynet** [comment]
Now imagemin/imagemin-mozjpeg#3 has been resolved and that package provides the same functionality as this module. (Y)

**Comment by matthewdolman** [comment]
I still experience this issue in windows 10.  @maranomynet's suggestion of using mozjpeg is not suitable for me as mozjepg is a lossy encoder and it is not possible to get full marks on google page speed insights with it.

Is there an easy way around this?

**Comment by triplumix** [comment]
Same issue. 
```
Creating an optimized production build

Failed to compile.

./assets/images/banner/1.jpg
Error: write EOF
```

**Comment by stareu** [comment]
In my case the problem was the size of the images.
They took 1 MB or more.
I optimized them with [tinypng.com](https://tinypng.com/) and the error is gone.
